# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 12) do

  create_table "bcrmbs", :force => true do |t|
    t.column "name",   :string
    t.column "bckey",  :string
    t.column "usr_id", :integer
  end

  create_table "exprtypes", :force => true do |t|
    t.column "name",   :string
    t.column "usr_id", :integer
  end

  create_table "frgmnts", :force => true do |t|
    t.column "name",         :string
    t.column "scrapeexpr",   :text
    t.column "exprtype",     :string
    t.column "frgtxt",       :text
    t.column "inputurl",     :string
    t.column "parent_id",    :integer
    t.column "rpt_id",       :integer
    t.column "outputrpt_id", :integer
    t.column "exprtype_id",  :integer
    t.column "usr_id",       :integer
  end

  create_table "outputrpts", :force => true do |t|
    t.column "name",             :string
    t.column "rpt_id",           :integer
    t.column "finalfrgmnt_name", :string
    t.column "usr_id",           :integer
    t.column "outputrpttype_id", :integer
  end

  create_table "outputrpttypes", :force => true do |t|
    t.column "name",   :string
    t.column "usr_id", :integer
  end

  create_table "rpts", :force => true do |t|
    t.column "name",       :string
    t.column "uurl",       :string
    t.column "enddate",    :date
    t.column "symbl_id",   :integer
    t.column "usr_id",     :integer
    t.column "rpttype_id", :integer
  end

  create_table "rpttypes", :force => true do |t|
    t.column "name",   :string
    t.column "usr_id", :integer
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "symbls", :force => true do |t|
    t.column "name",   :string
    t.column "cname",  :string
    t.column "usr_id", :integer
  end

  create_table "usrs", :force => true do |t|
    t.column "login",           :string,   :limit => 80,                    :null => false
    t.column "salted_password", :string,   :limit => 40,                    :null => false
    t.column "email",           :string,   :limit => 60,                    :null => false
    t.column "first_name",      :string,   :limit => 40
    t.column "last_name",       :string,   :limit => 40
    t.column "salt",            :string,   :limit => 40,                    :null => false
    t.column "verified",        :boolean,                :default => false
    t.column "role",            :string,   :limit => 40
    t.column "security_token",  :string,   :limit => 40
    t.column "token_expiry",    :datetime
    t.column "deleted",         :boolean,                :default => false
  end

end
